import Head from 'next/head';
import { getPages } from '../lib/notion';
import { QueryDatabaseResponse } from '@notionhq/client/build/src/api-endpoints';
import Link from 'next/link';

type Props = {
  pages: QueryDatabaseResponse['results'];
};

export async function getStaticProps() {
  const data = await getPages();

  return {
    props: {
      pages: data.results,
    },
  };
}

export default function Home({ pages }: Props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ul>
        {pages.map((x) => (
          <li key={x.id}>
            <Link href={`/${x.id}`}>{x.id}</Link>
          </li>
        ))}
      </ul>
    </>
  );
}
